(function(props,context) {
        Core.utils.renderBootstrap({
          elId:'bs-6',
          componentName:'ContactFormHours',
          props:props,
          context:context,
          contextKey:'context-bs-1',
          radpack:""
        });
      })({"structuredHours":[{"hour":{"day":"Monday","dayOfWeek":1,"openTime":"09:00","closeTime":"17:00","byAppointmentOnly":false,"closed":false}},{"hour":{"day":"Tuesday","dayOfWeek":2,"openTime":"09:00","closeTime":"17:00","byAppointmentOnly":false,"closed":false}},{"hour":{"day":"Wednesday","dayOfWeek":3,"openTime":"09:00","closeTime":"17:00","byAppointmentOnly":false,"closed":false}},{"hour":{"day":"Thursday","dayOfWeek":4,"openTime":"09:00","closeTime":"17:00","byAppointmentOnly":false,"closed":false}},{"hour":{"day":"Friday","dayOfWeek":5,"openTime":"09:00","closeTime":"17:00","byAppointmentOnly":false,"closed":false}},{"hour":{"day":"Saturday","dayOfWeek":6,"openTime":"09:00","closeTime":"17:00","byAppointmentOnly":false,"closed":false}},{"hour":{"day":"Sunday","dayOfWeek":0,"openTime":"09:00","closeTime":"17:00","byAppointmentOnly":false,"closed":false}}],"staticContent":{"today":"Today","submitButtonLoadingLabel":"Sending","contactFormResponseErrorMessage":"Something went wrong while sending your message, please try again later","defaultCancelButtonLabel":"Cancel","byAppointment":"By Appointment","defaultSubmitButtonLabel":"Send","closed":"Closed","termsOfSerivce":"Terms of Service","recaptchaDisclosure":"This site is protected by reCAPTCHA and the Google {privacyPolicy} and {termsOfSerivce} apply.","emailValidationErrorMessage":"Please enter a valid email address.","mapCTA":"Get directions","privacyPolicyURL":"https:\u002F\u002Fpolicies.google.com\u002Fprivacy","requiredValidationErrorMessage":"Please fill in this required field","openToday":"Open today","privacyPolicy":"Privacy Policy","termsOfSerivceURL":"https:\u002F\u002Fpolicies.google.com\u002Fterms"},"collapsible":false,"widgetId":"dc2223a2-9460-4d33-afe2-2e99a4a0feec","section":"alt","category":"neutral","locale":"en-PK","renderMode":"PUBLISH"},{"widgetId":"dc2223a2-9460-4d33-afe2-2e99a4a0feec","widgetType":"CONTACT","widgetPreset":"contact7","order":5,"section":"alt","category":"neutral","fontSize":"medium","fontFamily":"alternate","group":"Content","groupType":"Default"});